export const c_codes = [

    { flag: require('./../media/images/naija_flag.png'), value: '+234' },
    { flag: require('./../media/images/naija_flag.png'), value: '+111' },
    { flag: require('./../media/images/naija_flag.png'), value: '+123' },
    { flag: require('./../media/images/naija_flag.png'), value: '+456' },
    { flag: require('./../media/images/naija_flag.png'), value: '+789' },
    { flag: require('./../media/images/naija_flag.png'), value: '+901' },
    { flag: require('./../media/images/naija_flag.png'), value: '+235' },
    { flag: require('./../media/images/naija_flag.png'), value: '+346' },
    { flag: require('./../media/images/naija_flag.png'), value: '+908' },
    { flag: require('./../media/images/naija_flag.png'), value: '+876' },
    { flag: require('./../media/images/naija_flag.png'), value: '+176' },
    { flag: require('./../media/images/naija_flag.png'), value: '+954' },
    { flag: require('./../media/images/naija_flag.png'), value: '+932' },
    { flag: require('./../media/images/naija_flag.png'), value: '+219' },
    { flag: require('./../media/images/naija_flag.png'), value: '+256' },
    { flag: require('./../media/images/naija_flag.png'), value: '+549' },
    { flag: require('./../media/images/naija_flag.png'), value: '+098' },
    { flag: require('./../media/images/naija_flag.png'), value: '+931' },
    { flag: require('./../media/images/naija_flag.png'), value: '+345' },
    { flag: require('./../media/images/naija_flag.png'), value: '+476' },
    { flag: require('./../media/images/naija_flag.png'), value: '+865' },
    { flag: require('./../media/images/naija_flag.png'), value: '+631' },
    { flag: require('./../media/images/naija_flag.png'), value: '+871' },
    { flag: require('./../media/images/naija_flag.png'), value: '+777' },
]