export const icons = {
    open_scan: require('./../media/icons/open-scan.png'),
    eye: require('./../media/icons/eye.png'),
    eye_slash: require('./../media/icons/eye_slash.png'),
    arrow_back_icon: require('./../media/icons/arrow_back_icon.png'),
    arrow_front_icon: require('./../media/icons/arrow_front_icon.png'),
    eye_slash_modal: require('./../media/icons/eye_slash_modal.png'),
    mark_green_round: require('./../media/icons/mark_green_round.png'),
    
    tabs: {
        home: require('./../media/icons/home.png'),
        home_active: require('./../media/icons/home_active.png'),
        bridge: require('./../media/icons/bridge.png'),
        bridge_active: require('./../media/icons/bridge_active.png'),
        feeds: require('./../media/icons/feed.png'),
        feeds_active: require('./../media/icons/feed_active.png'),
        invest: require('./../media/icons/invest_active.png'),
        invest_active: require('./../media/icons/invest.png'),
    },
    
    side_bar: require('./../media/icons/side_bar.png'),
    sort_recent: require('./../media/icons/sort_recent.png'),
    sort_recent_light: require('./../media/icons/sort_recent_light.png'),
    wallet_eye: require('./../media/icons/wallet_eye.png'),
    plus_balance: require('./../media/icons/plus_balance.png'),
    angle_down_assets: require('./../media/icons/angle_down_assets.png'),
    search_assets: require('./../media/icons/search_assets.png'),
    cancel: require('./../media/icons/cancel.png'),
    check_dark: require('./../media/icons/check_dark.png'),
    eye_darker: require('./../media/icons/eye_darker.png'),
    invest_active: require('./../media/icons/invest_active.png'),
    wallet_active: require('./../media/icons/wallet_active.png'),
    angle_down_active: require('./../media/icons/angle_down_active.png'),
    cancel_dark: require('./../media/icons/cancel_dark.png'),
    trash_red: require('./../media/icons/trash_red.png'),
    ug_dark: require('./../media/icons/ug_dark.png'),
    pp_dark: require('./../media/icons/pp_dark.png'),
    support_dark: require('./../media/icons/support_dark.png'),
    sm_dark: require('./../media/icons/sm_dark.png'),
    check_light: require('./../media/icons/check_light.png'),
    
    
    dark: {
        eye: require('./../media/icons/eye.png'),
        eye_slash: require('./../media/icons/eye_slash.png'),
        copy: require('./../media/icons/copy.png'),
        side_bar: require('./../media/icons/side_bar.png'),
        history: require('./../media/icons/recent_dark.png'),
        search: require('./../media/icons/search.png'),
        angle_left: require('./../media/icons/angle_left.png'),
        home: require('./../media/icons/home.png'),
        bridge: require('./../media/icons/bridge.png'),
        feeds: require('./../media/icons/feed.png'),
        invest: require('./../media/icons/invest.png'),
        deposit: require('./../media/icons/deposit_light.png'),
        swap: require('./../media/icons/swap_light.png'),
        withdraw: require('./../media/icons/withdraw_light.png'),
        cancel: require('./../media/icons/cancel_dark.png'),
        angle_down: require('./../media/icons/angle_down.png'),
        info: require('./../media/icons/info.png'),
        arrow_right: require('./../media/icons/arrow_right.png'),
        more: require('./../media/icons/more.png'),
        wallet_scan: require('./../media/icons/wallet_scan.png'),
        swap_modal: require('./../media/icons/swap_modal.png'),
        faq: require('./../media/icons/faq.png'),
        pp: require('./../media/icons/pp.png'),
        support: require('./../media/icons/support.png'),
        socials: require('./../media/icons/socials.png'),
        person: require('./../media/icons/person.png'),
        track: require('./../media/icons/track.png'),
        info_pry_500: require('./../media/icons/info_pry_500.png'),
    },
    
    light: {
        plus: require('./../media/icons/plus_light.png'),
        eye_slash: require('./../media/icons/eye_slash_light.png'),
        angle_down: require('./../media/icons/angle_down_light.png'),
        deposit: require('./../media/icons/deposit_light.png'),
        info: require('./../media/icons/info.png'),
        swap: require('./../media/icons/swap_light.png'),
        withdraw: require('./../media/icons/withdraw_light.png'),
        buy: require('./../media/icons/buy_light.png'),
        sell: require('./../media/icons/sell_light.png'),
        angle_right: require('./../media/icons/angle_right_light.png'),
        est: require('./../media/icons/est_light.png'),
        bridge_light_r: require('./../media/icons/bridge_light_r.png'),
    },
    
    active: {
        home: require('./../media/icons/home_active.png'),
        bridge: require('./../media/icons/bridge_active.png'),
        feeds: require('./../media/icons/feed_active.png'),
        invest: require('./../media/icons/invest_active.png'),
        swap: require('./../media/icons/swap_active.png'),
        check: require('./../media/icons/check_active.png'),
        copy: require('./../media/icons/copy_active.png'),
        plus: require('./../media/icons/plus_active.png'),
    },

    angle_up_green: require('./../media/icons/angle_up_green.png'),
    angle_down_green: require('./../media/icons/angle_down_green.png'),
    logout_red: require('./../media/icons/logout_red.png'),
    check_green: require('./../media/icons/check_green.png'),
    plus_pry_400: require('./../media/icons/plus_pry_400.png'),
}