export const images = {
    logo: require('./../media/images/criflogo.png'),
    user_dp_1: require('./../media/images/user_dp_1.png'),
    btc_logo: require('./../media/images/btc_logo.png'),
    all_assets: require('./../media/images/all_assets.png'),
    swipe_bg_1: require('./../media/images/swipe_bg_1.png'),
    swipe_bg_2: require('./../media/images/swipe_bg_2.png'),
    graph_demo: require('./../media/images/graph_demo.png'),
    naija_flag: require('./../media/images/naija_flag.png'),
    pie_demo: require('./../media/images/pie_demo.png'),
    line_demo: require('./../media/images/line_demo.png'),
    line_demo_2: require('./../media/images/line_demo_2.png'),
    wallet_scan: require('./../media/images/wallet_scan.png'),
    eth: require('./../media/images/eth.png'),
    usdt: require('./../media/images/usdt.png'),
    btc_i: require('./../media/images/btc_logo_i.png'),
    splash_gif: require('./../media/images/crifs-gifs.gif'),
    splash_gif_2: require('./../media/images/cg_2.gif'),
}