export const tokens = [
    {
        logo: require('./../media/images/btc_logo.png'),
        ticker: 'BTC',
        name: 'Bitcoin',
        amount: 0.06254,
        amount_in_bucks: 1835.45,
        type: 'crypto',
    },
    {
        logo: require('./../media/images/sol.png'),
        ticker: 'SOL',
        name: 'Solana',
        amount: 0.06254,
        amount_in_bucks: 1835.45,
        type: 'crypto',
    },
    {
        logo: require('./../media/images/euro.png'),
        ticker: 'Eur',
        name: 'Euro',
        amount: 0.06254,
        amount_in_bucks: 1835.45,
        type: 'fiat',
    },
    {
        logo: require('./../media/images/naira.png'),
        ticker: 'NGN',
        name: 'Nigerian Naira',
        amount: 24762.00,
        amount_in_bucks: 33.46,
        type: 'fiat',
    },
    {
        logo: require('./../media/images/usd.png'),
        ticker: 'USD',
        name: 'United States Dollar',
        amount: 0.06254,
        amount_in_bucks: 1835.45,
        type: 'fiat',
    },
    {
        logo: require('./../media/images/euro.png'),
        ticker: 'DEM',
        name: 'Euro',
        amount: 0.06254,
        amount_in_bucks: 1835.45,
        type: 'fiat',
    },
    {
        logo: require('./../media/images/naira.png'),
        ticker: 'DEM2',
        name: 'Nigerian Naira',
        amount: 24762.00,
        amount_in_bucks: 33.46,
        type: 'fiat',
    },
    {
        logo: require('./../media/images/eth.png'),
        ticker: 'ETH',
        name: 'Ethereum',
        amount: 24762.00,
        amount_in_bucks: 33.46,
        type: 'crypto',
    },
    {
        logo: require('./../media/images/usdt.png'),
        ticker: 'USDT',
        name: 'US DOllar Token',
        amount: 24762.00,
        amount_in_bucks: 33.46,
        type: 'crypto',
    },
]